chat_model:
  init_args:
    model: google/gemini-2.5-flash-lite-preview-09-2025
    model_provider: openai
    api_key:
    base_url: https://openrouter.ai/api/v1
  max_requests_per_minute: 500
  max_requests_per_day: 2000

image_generator:
  class_path: tools.ImageGeneratorNanobananaYunwuAPI
  init_args:
    api_key:
  max_requests_per_minute: 10
  max_requests_per_day: 500

video_generator:
  class_path: tools.VideoGeneratorOmniYunwuAPI
  init_args:
    api_key:
    t2v_model: omni-flash
    i2v_model: omni-flash
    seconds: 8
    enable_upsample: false
  max_requests_per_minute: 2
  max_requests_per_day: 10

working_dir: .working_dir/idea2video
